- name: Ansible Pet-clinic in AWS | Provision all required infrastructure
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
     -  { role: aws-network, tags: ['network']}
     -  { role: aws-security, tags: ['security']}
     -  { role: aws-ec2, tags: ['ec2']}

