- hosts: web
  vars:
    app: { user: petclinic, service: petclinic, filename: spring-petclinic-1.5.1.jar, desc: Spring Boot Petclinic }
  tasks:
  - name: install java
    become: true
    apt:
      update_cache: yes
      name: default-jre
      state: latest
  - name: create user {{app.user}}
    become: true
    user:
      name: "{{app.user}}"
  - name: copy jar file
    become: true
    copy:
      src: ./files/{{app.filename}}
      dest: /home/{{app.user}}/{{app.filename}}
      owner: "{{app.user}}"
      mode: 0744
  - name: create systemd config
    become: true
    template:
      src: ./templates/spring-boot.service.j2
      dest: /etc/systemd/system/{{app.service}}.service
      owner: "{{app.user}}"
      mode: 0644
  - name: "{{app.service}} is running"
    become: true
    systemd:
      state: restarted
      daemon_reload: yes
      name: "{{app.service}}"

