---

- hosts: all
  vars:
    application_name: spring-petclinic-1.5.1
    service_name: myservice
  gather_facts: True
  tasks:
    - name: Update cache and install java
      apt:
        name: default-jre
        state: present
        update_cache: true
      become: true
      become_user: root
    - name: Copy petclinic executable to hosts
      copy:
        src: /project/spring-petclinic/target/{{application_name}}.jar
        dest: /opt/{{application_name}}.jar
        owner: ubuntu
        group: ubuntu
        mode: 0755
      become: true
    - name: create executable petclinic service
      template:
        src: service.j2
        dest: /etc/systemd/system/{{service_name}}.service
        mode: 0755
      become: true
    - name: restart petclinic service
      systemd:
        state: restarted
        daemon_reload: yes
        name: "{{service_name}}"
      become: true
    - name: Check that you can connect (GET) to a page and it returns a status 200
      uri:
        url: http://localhost:8080
      register: webpage
      until: webpage.status == 200
      retries: 10
      delay: 2