- hosts: all
  tasks: 
  - name: 'Ensure java is installed'
    apt:
      update_cache: yes
      name: default-jre
    become: true
  - name: 'Ensure spring boot app exists on remote machine'
    copy: 
      src: /project/spring-petclinic/target/spring-petclinic-1.5.1.jar
      dest: /home/ubuntu/
      mode: "a+rx"
  - name: 'Ensure systemd script exists'
    copy:
      src: petclinic.service
      dest: /etc/systemd/system/
      mode: "a+rx"
    become: true
  - name: 'Ensure sevice is registered'
    systemd:
      name: petclinic.service
      enabled: yes
      state: started
    become: true
