---
# tasks file for nginx
- name: Ensure nginx is installed
  apt:
    update_cache: yes
    name: nginx
- name: Ensure nginx is configured
  copy:
    src: nginx.conf
    dest: /etc/nginx/sites-available/default
  notify: configured_nginx