- hosts: all
  tasks: 
  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
      update_cache: yes
    become: true
  - name: 'Ensure java is installed'
    apt:
      name: default-jre
    become: true