---

- name: Ensure latest nginx is installed
  apt:
    update_cache: yes
    name: nginx
    state: latest

- name: Ensure hosts are added to load balancer config
  template:
      src: "default.j2"
      dest: "/etc/nginx/sites-available/default"
  notify: 'reload nginx'


