---
- name: install nginx
  apt:
    update_cache: yes
    name: nginx
    state: latest
- name: replace default config
  template:
    src: nginx.site.default.j2
    dest: /etc/nginx/sites-available/default
    mode: 0644
  notify: "restart nginx"
