- hosts: web
  gather_facts: true
  become: yes
  tasks:
  - name: Update the repository cache and ensure that package "nginx" is present
    apt:
      name: nginx
      state: present
      update_cache: yes

  - name: insert/update location configuration block in default config
    lineinfile:
      path: /etc/nginx/sites-available/default
      regexp: '^\s*try_files \$uri \$uri/ =404;'
      line: 'proxy_pass {{ proxy_pet_clinic_url }};'
    notify: "nginx config changed"

  - name: Ensure systemd service ist started
    systemd: state=restarted name=nginx daemon_reload=yes

  handlers:
  - name: restart nginx
    service: name=nginx state=restarted
    listen: "nginx config changed"

  - name: Check that you can connect (GET) to a page and it returns a status 200
    uri:
      url: http://localhost:80  # URL on the target system
    register: call_result
    until: call_result.status == 200
    retries: 20
    delay: 1
    listen: "nginx config changed"

  vars:
    - proxy_pet_clinic_url: http://127.0.0.1:8080
