region: eu-west-1
ami-image: ami-6d48500b #depends on the region
accountid: 604370441254
application_name: ansible-aws-pedclinic
vpc_cidr_block: 10.0.10.0/16
cost_center: DevOps

env: prod

subnetwork_def:
    # public subnetworks
    - {az: "{{region}}a", cidir: 10.0.1.0/24, Name: "{{application_name}}-nw-public-a", nat: "yes", Networkkind: public, CostCenter: "{{cost_center}}", Usage: "ELB" }
    - {az: "{{region}}b", cidir: 10.0.2.0/24, Name: "{{application_name}}-nw-public-b", nat: "no" , Networkkind: public, CostCenter: "{{cost_center}}", Usage: "APP" }
    - {az: "{{region}}c", cidir: 10.0.3.0/24, Name: "{{application_name}}-nw-public-c", nat: "no" , Networkkind: public, CostCenter: "{{cost_center}}", Usage: "APP" }
